### ISSUE TITLE
Issue when running: "openpyn fi -t 10"

### ISSUE THREAD

**Issue by Cursewords** [jotyGill/openpyn-nordvpn#105]
I get this error when running the command: "openpyn fi -t 10"

```
None
Traceback (most recent call last):
  File "/usr/local/bin/openpyn", line 9, in <module>
    load_entry_point('openpyn==2.4.0', 'console_scripts', 'openpyn')()
  File "/usr/local/lib/python3.5/dist-packages/openpyn/openpyn.py", line 133, in main
    args.skip_dns_patch, args.silent, args.nvram, args.openvpn_options)
  File "/usr/local/lib/python3.5/dist-packages/openpyn/openpyn.py", line 309, in run
    connection = connect(aserver, port, silent, test, skip_dns_patch, openvpn_options)
  File "/usr/local/lib/python3.5/dist-packages/openpyn/openpyn.py", line 713, in connect
    + openvpn_options.split(), check=True)
AttributeError: 'NoneType' object has no attribute 'split'
```

**Comment by jotyGill** [comment]
That was a silly mistake, Please update openpyn.
`sudo pip3 install --upgrade openpyn`

**Comment by Cursewords** [comment]
Thank you very much, it's working. You can close the issue.

**Comment by Cursewords** [comment]
Thank you very much, it's working. We appreciate your work :)
