### ISSUE TITLE
Errors at startup

### ISSUE THREAD

**Issue by oliviermrs** [jotyGill/openpyn-nordvpn#128]
```
Tue Mar 27 17:22:22 2018 Data Channel Encrypt: Cipher 'AES-256-GCM' initialized with 256 bit key
Tue Mar 27 17:22:22 2018 Data Channel Decrypt: Cipher 'AES-256-GCM' initialized with 256 bit key
Tue Mar 27 17:22:22 2018 ROUTE_GATEWAY 192.168.0.254/255.255.255.0 IFACE=enp7s0 HWADDR=34:e6:d7:67:a6:3f
Tue Mar 27 17:22:22 2018 TUN/TAP device tun0 opened
Tue Mar 27 17:22:22 2018 TUN/TAP TX queue length set to 100
Tue Mar 27 17:22:22 2018 do_ifconfig, tt->did_ifconfig_ipv6_setup=0
Tue Mar 27 17:22:22 2018 /sbin/ip link set dev tun0 up mtu 1500
Tue Mar 27 17:22:22 2018 /sbin/ip addr add dev tun0 10.8.8.163/24 broadcast 10.8.8.255
Tue Mar 27 17:22:22 2018 /sbin/ip route add 82.102.18.109/32 via 192.168.0.254
Tue Mar 27 17:22:22 2018 /sbin/ip route add 0.0.0.0/1 via 10.8.8.1
Tue Mar 27 17:22:22 2018 /sbin/ip route add 128.0.0.0/1 via 10.8.8.1
Tue Mar 27 17:22:22 2018 Initialization Sequence Completed
Tue Mar 27 17:22:22 2018 MANAGEMENT: Client connected from [AF_INET]127.0.0.1:7015
Traceback (most recent call last):
  File "/usr/bin/openpyn-management", line 9, in <module>
    load_entry_point('openpyn==2.1.1', 'console_scripts', 'openpyn-management')()
  File "/usr/lib/python3/dist-packages/openpyn/management/management.py", line 34, in show
    notification.show()
GLib.Error: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.Notifications was not provided by any .service files (2)
Tue Mar 27 17:22:22 2018 MANAGEMENT: TCP recv error: Connection reset by peer
Tue Mar 27 17:22:22 2018 MANAGEMENT: Client disconnected
```

I'm stuck with this. Any idea to resolve this?

**Comment by jotyGill** [comment]
You are using an old version openpyn==2.1.1
I am about to push 2.5.0,  please upgrade to at least 2.4.2.
`sudo pip3 install openpyn --upgrade` 
check version `openpyn -v`

or fetch the latest one.

remove old install by finding files and removing them.
`sudo find -name openpyn`
