### ISSUE TITLE
Help with custom kill-switch on IP tables and openpyn

### ISSUE THREAD

**Issue by luispuerto** [jotyGill/openpyn-nordvpn#161]
I need a need a little bit help with your wonderful app. I finally make it work, as [I already told you](https://github.com/jotyGill/openpyn-nordvpn/issues/137#issuecomment-395724821).  

The problem now is, I would like to have the kill switch, but the app kill witch isn't working really good, or at least for me so I would like to keep the kill switch I had in place with OpenVPN. 

The error I get when I run your app with the kill switch is the following one: 

```sh 
$ openpyn us -f --allow 22 123 53 --netflix
```

```
Flushing iptables INPUT and OUTPUT chains AND Applying default Rules
According to NordVPN, Least Busy 10 Servers, In US With 'Load' less than 70 Which Support OPENVPN-UDP , netflix = True are : [['us956', 4], ['us957', 4], ['us959', 4], ['us961', 4], ['us1093', 4], ['us1103', 4], ['us1122', 4], ['us1150', 4], ['us1152', 4], ['us1154', 4]]

Pinging Server us956 min/avg/max/mdev =  [151, 152, 153, 0]

Pinging Server us957 min/avg/max/mdev =  [155, 156, 157, 0]

Pinging Server us959 min/avg/max/mdev =  [148, 148, 149, 0]

Pinging Server us961 min/avg/max/mdev =  [158, 159, 159, 0]

Pinging Server us1093 min/avg/max/mdev =  [223, 225, 227, 1]

Pinging Server us1103 min/avg/max/mdev =  [159, 165, 169, 4]

Pinging Server us1122 min/avg/max/mdev =  [157, 158, 159, 0]

Pinging Server us1150 min/avg/max/mdev =  [186, 192, 195, 3]

Pinging Server us1152 min/avg/max/mdev =  [188, 192, 200, 5]

Pinging Server us1154 min/avg/max/mdev =  [143, 147, 151, 3]

Top 10 Servers with best Ping are: ['us1154', 'us959', 'us956', 'us957', 'us1122', 'us961', 'us1103', 'us1150', 'us1152', 'us1093']


Device "bonding_masters" does not exist.
Traceback (most recent call last):
  File "/usr/local/bin/openpyn", line 11, in <module>
    load_entry_point('openpyn==2.6.0', 'console_scripts', 'openpyn')()
  File "/usr/local/lib/python3.5/dist-packages/openpyn/openpyn.py", line 130, in main
    args.skip_dns_patch, args.silent, args.nvram, args.openvpn_options)
  File "/usr/local/lib/python3.5/dist-packages/openpyn/openpyn.py", line 313, in run
    network_interfaces = get_network_interfaces()
  File "/usr/local/lib/python3.5/dist-packages/openpyn/openpyn.py", line 663, in get_network_interfaces
    interface_out = subprocess.check_output(["ip", "addr", "show", interface])
  File "/usr/lib/python3.5/subprocess.py", line 316, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 398, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ip', 'addr', 'show', 'bonding_masters']' returned non-zero exit status 1
```

I've flushed the `iptables` before just in case, but if I check it again I get: 

```sh 
$ iptables -S
```

```
-P INPUT DROP
-P FORWARD ACCEPT
-P OUTPUT ACCEPT
-A INPUT -i lo -j ACCEPT
-A INPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A INPUT -p icmp -m icmp --icmp-type any -j ACCEPT
-A INPUT -s 127.0.0.0/8 -j DROP
-A OUTPUT -o lo -j ACCEPT
```

So for that reason I would like to keep my own configuration that is the following one: 

```sh 
$ iptables -S
```

```
-P INPUT ACCEPT
-P FORWARD ACCEPT
-P OUTPUT ACCEPT
-A FORWARD -i tun0 -o eth0 -m state --state RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -i eth0 -o tun0 -j ACCEPT
-A OUTPUT -o tun0 -m comment --comment vpn -j ACCEPT
-A OUTPUT -o eth0 -p icmp -m comment --comment icmp -j ACCEPT
-A OUTPUT -d 192.168.1.0/24 -o eth0 -m comment --comment lan -j ACCEPT
-A OUTPUT -o eth0 -p udp -m udp --dport 1194 -m comment --comment openvpn -j ACCEPT
-A OUTPUT -o eth0 -p tcp -m tcp --sport 22 -m comment --comment ssh -j ACCEPT
-A OUTPUT -o eth0 -p udp -m udp --dport 123 -m comment --comment ntp -j ACCEPT
-A OUTPUT -o eth0 -p udp -m udp --dport 53 -m comment --comment dns -j ACCEPT
-A OUTPUT -o eth0 -p tcp -m tcp --dport 53 -m comment --comment dns -j ACCEPT
-A OUTPUT -o eth0 -j DROP
```

```sh 
$ iptables -L --line-numbers
```

```
Chain INPUT (policy ACCEPT)
num  target     prot opt source               destination

Chain FORWARD (policy ACCEPT)
num  target     prot opt source               destination
1    ACCEPT     all  --  anywhere             anywhere             state RELATED,ESTABLISHED
2    ACCEPT     all  --  anywhere             anywhere

Chain OUTPUT (policy ACCEPT)
num  target     prot opt source               destination
1    ACCEPT     all  --  anywhere             anywhere             /* vpn */
2    ACCEPT     icmp --  anywhere             anywhere             /* icmp */
3    ACCEPT     all  --  anywhere             192.168.1.0/24       /* lan */
4    ACCEPT     udp  --  anywhere             anywhere             udp dpt:openvpn /* openvpn */
5    ACCEPT     tcp  --  anywhere             anywhere             tcp spt:ssh /* ssh */
6    ACCEPT     udp  --  anywhere             anywhere             udp dpt:ntp /* ntp */
7    ACCEPT     udp  --  anywhere             anywhere             udp dpt:domain /* dns */
8    ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:domain /* dns */
9    DROP       all  --  anywhere             anywhere
```

The problem is, I try to run you app without choosing an specific server I get nothing. I guess that the app needs to connect to internet to choose what server. 

**Could you tell me what rule should I add to the `iptables` to allow the normal function of the app?**

**THANKS!**

Your app it's really great! :heart_eyes:

**Comment by jotyGill** [comment]
Hi There,
Sorry for the late reply. The way that I handle that issue is I grab the ip address of the chosen server (at that moment) on the fly then allow traffic to it. Another way would be to allow the whole range used by NordVPN (if they do have one range (doubt it) or multiple ranges)
I have redone some iptables rules and things in the latest release try that.

**Comment by luisspuerto** [comment]
Hey @jotyGill ! thanks for the info! 

I've been using your app since then, but I haven't needed to change the server so with my config as it's  works well. 

When I have a moment I'll try to work it out with the new version and the new kill switch.
