### ISSUE TITLE
Error while trying to connect

### ISSUE THREAD

**Issue by orangecoloured** [jotyGill/openpyn-nordvpn#164]
Today I bumped into this.
```
Traceback (most recent call last):
  File "/usr/local/bin/openpyn", line 9, in <module>
    load_entry_point('openpyn==2.6.0', 'console_scripts', 'openpyn')()
  File "/usr/local/lib/python3.5/dist-packages/openpyn/openpyn.py", line 130, in main
    args.skip_dns_patch, args.silent, args.nvram, args.openvpn_options)
  File "/usr/local/lib/python3.5/dist-packages/openpyn/openpyn.py", line 306, in run
    dedicated, double_vpn, tor_over_vpn, anti_ddos, netflix)
  File "/usr/local/lib/python3.5/dist-packages/openpyn/openpyn.py", line 373, in find_better_servers
    netflix=netflix)
  File "/usr/local/lib/python3.5/dist-packages/openpyn/api.py", line 31, in get_data_from_api
    json_response = get_json(url)
  File "/usr/local/lib/python3.5/dist-packages/openpyn/api.py", line 14, in get_json
    json_response = requests.get(url, headers=headers).json()
  File "/usr/local/lib/python3.5/dist-packages/requests/models.py", line 896, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

Tried reinstalling it. For some reason pip3 was not found so had to reinstall it too.
Is it something related to the python environment or something else?

**Comment by orangecoloured** [comment]
Nevermind. It just started working again.
