### ISSUE TITLE
Python 3.6.5

### ISSUE THREAD

**Issue by mrahmadt** [jotyGill/openpyn-nordvpn#182]
Hello

I'm trying to install openpyn in Ubuntu 18.04.1 with Python 3.6.5 but I'm getting the following error

`
    
        sudo python3 -m pip install --upgrade openpyn
    The directory '/home/smartgw/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If     executing pip with sudo, you may want sudo's -H flag.
    The directory '/home/smartgw/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
    Collecting openpyn
          Downloading https://files.pythonhosted.org/packages/d6/d7/1d43a3de047d62831faa808b9bad792d1ff98a7a1bd2e53a772ea1fde2a9/openpyn-2.7.1.tar.gz (61kB)
            100% |################################| 61kB 300kB/s
            Complete output from command python setup.py egg_info:
            Traceback (most recent call last):
              File "<string>", line 1, in <module>
              File "/tmp/pip-build-m7hq0snf/openpyn/setup.py", line 4, in <module>
                from openpyn import __data_files__, __version__
              File "/tmp/pip-build-m7hq0snf/openpyn/openpyn/__init__.py", line 5, in <module>
            import verboselogs
        ModuleNotFoundError: No module named 'verboselogs'

    ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-m7hq0snf/openpyn/`

`sg@sg:~$ pip3 --version
pip 9.0.1 from /usr/lib/python3/dist-packages (python 3.6)
sg@sg:~$ python3 --version
Python 3.6.5`

Any advice?

Thanks

**Comment by android-808** [comment]
I had this with Debian Stretch as well.

As a temporary fix, try sudo python3 -m pip install --upgrade verboselogs before running the openpyn install command.
