### ISSUE TITLE
MANAGEMENT: Client disconnected

### ISSUE THREAD

**Issue by trancef0rmer** [jotyGill/openpyn-nordvpn#190]
Hello! 
I am using openpyn 2.7.4 and I get that error on connection: 
`Wed Aug 22 17:51:22 2018 /usr/local/lib/python3.6/dist-packages/openpyn/scripts/update-systemd-resolved.sh tun0 1500 1585 10.8.8.234 255.255.255.0 init
<14>Aug 22 17:51:22 update-systemd-resolved.sh: Link 'tun0' coming up
<14>Aug 22 17:51:22 update-systemd-resolved.sh: Adding DNS Routed Domain .
<14>Aug 22 17:51:22 update-systemd-resolved.sh: Adding IPv4 DNS Server 103.86.96.100
<14>Aug 22 17:51:22 update-systemd-resolved.sh: Adding IPv4 DNS Server 103.86.99.100
<14>Aug 22 17:51:22 update-systemd-resolved.sh: SetLinkDNS(5 2 2 4 103 86 96 100 2 4 103 86 99 100)
Traceback (most recent call last):
  File "/usr/local/bin/openpyn-management", line 11, in <module>
    load_entry_point('openpyn==2.7.4', 'console_scripts', 'openpyn-management')()
  File "/usr/local/lib/python3.6/dist-packages/openpyn/management/management.py", line 166, in main
    return show(args.do_notify)
  File "/usr/local/lib/python3.6/dist-packages/openpyn/management/management.py", line 68, in show
    notification.show()
GLib.Error: g-dbus-error-quark: Unexpected reply type (16)
<14>Aug 22 17:51:22 update-systemd-resolved.sh: SetLinkDomains(5 1 . true)
Wed Aug 22 17:51:22 2018 /sbin/ip route add 86.105.9.91/32 via 192.168.1.1
Wed Aug 22 17:51:22 2018 /sbin/ip route add 0.0.0.0/1 via 10.8.8.1
Wed Aug 22 17:51:22 2018 /sbin/ip route add 128.0.0.0/1 via 10.8.8.1
Wed Aug 22 17:51:22 2018 Initialization Sequence Completed
Wed Aug 22 17:51:22 2018 MANAGEMENT: TCP send error: Connection reset by peer
Wed Aug 22 17:51:22 2018 MANAGEMENT: Client disconnected
`
I get a new IP anyway, but is this a secure connection ?
Thanks

**Comment by trancef0rmer** [comment]
Hello! 
Thanks for the answer! 
I'm using Ubuntu 18.04. After I posted this issue, it happened a couple of times and now it works like it should. I guess it's due to system updates
