### ISSUE TITLE
Amend openpyn us --netflix output

### ISSUE THREAD

**Issue by ickam** [jotyGill/openpyn-nordvpn#195]
Recently only several nordVpn servers work with US Netflix. These servers are: #707-710, 722-725. Please provide a fix or let me know which lines of code I need to change

**Comment by jotyGill** [comment]
Hi there,
Yeah I heard they keep blocking servers. NordVPN has also added more servers. I don't have Netfix, could you please have a look at newer server (higher ranges) and let me know which ones work. They are posted here (https://support.nordvpn.com/#/General-Info/1047407532/How-to-securely-watch-Netflix-with-NordVPN.htm). If you would like to commit the changes yourself, please clone the 'test' branch and edit the openpyn/filters.py at line 52. Thank you
` git clone --branch test https://github.com/jotyGill/openpyn-nordvpn.git`

**Comment by ickam** [comment]
I amended US and UK server numbers and was going to test it locally before I submitted the commit, but I get errors:
```
~/openpyn-nordvpn $ sudo python3.6 -m pip install --upgrade -e
Traceback (most recent call last):
  File "/usr/lib/python3.6/pkgutil.py", line 412, in get_importer
    importer = sys.path_importer_cache[path_item]
KeyError: ''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.6/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/usr/lib/python3/dist-packages/pip/__init__.py", line 72, in <module>
    from pip.log import logger
  File "/usr/lib/python3/dist-packages/pip/log.py", line 9, in <module>
    import colorama, pkg_resources
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3095, in <module>
    @_call_aside
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3079, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3108, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 561, in _build_master
    ws = cls()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 554, in __init__
    self.add_entry(entry)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 610, in add_entry
    for dist in find_distributions(entry, True):
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1862, in find_distributions
    importer = get_importer(path_item)
  File "/usr/lib/python3.6/pkgutil.py", line 416, in get_importer
    importer = path_hook(path_item)
  File "<frozen importlib._bootstrap_external>", line 1324, in path_hook_for_FileFinder
  File "<frozen importlib._bootstrap_external>", line 102, in _path_isdir
FileNotFoundError: [Errno 2] No such file or directory'
```
What do I do?

**Comment by ickam** [comment]
Also there is something I do not understand. The link that you provided specifies that I can connect to a server in any country (bar a few) to access US netflix content. So on my windows laptop I connected to the fastest server in Ireland and it gives me the content that is available in the US
on doing the same on my raspberry pi with openpyn, it doesn't serve the content that was available on my windows laptop (madam secretary; grey's anatomy) - these are available in the US but not in Europe.

I suspect this has something to do with that Smartplay feature that Nordvpn rolled out recently. Is there any way openpyn could implement smartplay?

**Comment by jotyGill** [comment]
That's weird. Is python 3.6 your OS's native python version? or you have another version of python3 as well.
btw shouldn't the command include "." at the end?
try this.
`sudo python3 -m pip install --upgrade -e .`

I see the Smartplay system seems to use some form of proxies to reroute traffic instead of vpn connections. I got no idea how it works beyond that. Well, as long as we can directly vpn to servers that work with Netflix, it's alright.
