### ISSUE TITLE
List fails

### ISSUE THREAD

**Issue by thomasave** [jotyGill/openpyn-nordvpn#20]
When running `openpyn -l` I get the following error:
```
Traceback (most recent call last):
  File "/usr/bin/openpyn", line 730, in <module>
    args.tor_over_vpn, args.anti_ddos, args.test)
  File "/usr/bin/openpyn", line 47, in main
    list_all_countries()
  File "/usr/bin/openpyn", line 463, in list_all_countries
    for key in country_dic.keys():
NameError: name 'country_dic' is not defined
```

**Comment by jotyGill** [comment]
ah, forgot to change the name of country_dic to countries_mapping , should be fixed now :)
