### ISSUE TITLE
unable to run openpyn

### ISSUE THREAD

**Issue by atomGit** [jotyGill/openpyn-nordvpn#253]
manjaro/kde stable
openpyn-nordvpn 2.2.0.r314.g0b40481-1

i ran the same version of openpyn just a day or 2 ago and all was well, but now it won't run...

```
$ openpyn --help
Traceback (most recent call last):
  File "/usr/bin/openpyn", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3252, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3235, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3264, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'verboselogs' distribution was not found and is required by openpyn
```

python-verboselogs  1.7-3 is installed

**Comment by jotyGill** [comment]
That's weird.
openpyn seems to be installed at the os level (/usr/bin/openpyn), which is how it should be.
I see you installed it using the aur package.
looks like verboselogs isn't accessible at the os level. perhaps it was installed with (pip3 install --user ) or in a perticular virtual env you were using before?
I would uninstall it (`pip3 uninstall python-verboselogs`) then install it at the os level.
`sudo pip3 install -U python-verboselogs`

**Comment by atomGit** [comment]
it was installed at the OS level using pamac (also tried yay) - i don't know what pip3 is

i don;t know what changed, but one day it ran and the next it didn't, so something in a manjaro update must have caused this

**Comment by jotyGill** [comment]
python packages are hosted at pypi https://pypi.org/project/openpyn/.
pip is the tool that installs them, like apt or yay.
in Arch/manjaro pip3 might be just pip now (it's been a while since I used arch)
It could be that the update changed python to version 3.8 and now it's not accessing 3.7's libraries installed in a particular way.

run this `sudo python -m pip uninstall python-verboselogs`
then `sudo python -m pip install python-verboselogs`

**Comment by jotyGill** [comment]
Yep it is python version change to 3.8 , that's breaking stuff.

https://www.reddit.com/r/ManjaroLinux/comments/e9lu0x/stable_update_20191210_kernels_kde_cinnamon_pamac/

Might need to completely uninstall and reinstall openpyn.

**Comment by atomGit** [comment]
thanks for figuring this out

openpyn is not installed now and i'm not seeing anything in my home directory - is there anything else i need to remove?

and do i still need to run the commands in your last comment?

**Comment by jotyGill** [comment]
https://www.reddit.com/r/ManjaroLinux/search/?q=python&restrict_sr=1

looks like installed python scripts can't find previously installed libraries using 3.7

Reinstalling them would do the trick. (It wouldn't hurt but maybe even required.)
Now openpyn is installed using https://aur.archlinux.org/packages/openpyn-nordvpn/
I am not sure after this OS mess up when you uninstall it if it properly uninstalled these libraries or not.
First just simply install using yay, if it doesn't work. uninstall it in yay, then try uninstalling using pip `sudo python -m pip uninstall openpyn` then maybe uninstall the dependencies as well. then reinstall.

Edit: typo

**Comment by atomGit** [comment]
python-verboselogs was not installed - i remember specifically removing it from pamac when i removed openpyn - so i...

`$ yay openpyn-nordvpn`
then i...
`$ openpyn --help`
and got the same error as in the OP, so then i...
`$ sudo python -m pip install python-verboselogs`
and i got this...
```
Collecting python-verboselogs
  ERROR: Could not find a version that satisfies the requirement python-verboselogs (from versions: none)
ERROR: No matching distribution found for python-verboselogs
```

<details>
  <summary>full log</summary>

```bash
$ yay openpyn-nordvpn
1 aur/openpyn-nordvpn 2.2.0.r308.gbd993a0-1 (+9 0.09%) (Orphaned) 
    Easily connect to and switch between OpenVPN servers hosted by NordVPN
==> Packages to install (eg: 1 2 3, 1-3 or ^4)
==> 1
:: Checking for conflicts...
:: Checking for inner conflicts...
[Repo: 2]  pkcs11-helper-1.25.1-2  openvpn-2.4.8-1
[Aur: 1]  openpyn-nordvpn-2.2.0.r308.gbd993a0-1

  1 openpyn-nordvpn                          (Build Files Exist)
==> Packages to cleanBuild?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> a
:: Deleting (1/1): /home/atom/.cache/yay/openpyn-nordvpn
:: Downloaded PKGBUILD (1/1): openpyn-nordvpn
  1 openpyn-nordvpn                          (Build Files Exist)
==> Diffs to show?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> n
:: Parsing SRCINFO (1/1): openpyn-nordvpn
[sudo] password for atom: 
resolving dependencies...
looking for conflicting packages...

Packages (2) openvpn-2.4.8-1  pkcs11-helper-1.25.1-2

Total Installed Size:  1.30 MiB

:: Proceed with installation? [Y/n] y
(2/2) checking keys in keyring                        [############################] 100%
(2/2) checking package integrity                      [############################] 100%
(2/2) loading package files                           [############################] 100%
(2/2) checking for file conflicts                     [############################] 100%
(2/2) checking available disk space                   [############################] 100%
:: Processing package changes...
(1/2) installing pkcs11-helper                        [############################] 100%
(2/2) installing openvpn                              [############################] 100%
Optional dependencies for openvpn
    easy-rsa: easy CA and certificate handling
    pam: authenticate via PAM [installed]
:: Running post-transaction hooks...
(1/3) Reloading system manager configuration...
(2/3) Creating temporary files...
(3/3) Arming ConditionNeedsUpdate...
==> Making package: openpyn-nordvpn 2.2.0.r308.gbd993a0-1 (Thu 19 Dec 2019 06:37:11 AM EST)
==> Retrieving sources...
  -> Cloning openpyn-nordvpn git repo...
Cloning into bare repository '/home/atom/.cache/yay/openpyn-nordvpn/openpyn-nordvpn'...
remote: Enumerating objects: 65, done.
remote: Counting objects: 100% (65/65), done.
remote: Compressing objects: 100% (41/41), done.
remote: Total 4520 (delta 38), reused 44 (delta 24), pack-reused 4455
Receiving objects: 100% (4520/4520), 2.63 MiB | 2.39 MiB/s, done.
Resolving deltas: 100% (3549/3549), done.
==> Validating source files with sha512sums...
    openpyn-nordvpn ... Skipped
openvpn not satisfied, flushing install queue
==> Making package: openpyn-nordvpn 2.2.0.r308.gbd993a0-1 (Thu 19 Dec 2019 06:37:15 AM EST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Updating openpyn-nordvpn git repo...
Fetching origin
==> Validating source files with sha512sums...
    openpyn-nordvpn ... Skipped
==> Removing existing $srcdir/ directory...
==> Extracting sources...
  -> Creating working copy of openpyn-nordvpn git repo...
Cloning into 'openpyn-nordvpn'...
done.
==> Starting pkgver()...
==> Updated version: openpyn-nordvpn 2.2.0.r314.g0b40481-1
==> Sources are ready.
==> Making package: openpyn-nordvpn 2.2.0.r314.g0b40481-1 (Thu 19 Dec 2019 06:37:20 AM EST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> WARNING: Using existing $srcdir/ tree
==> Starting pkgver()...
==> Starting build()...
running build
running build_py
creating build
creating build/lib
creating build/lib/openpyn
copying openpyn/__init__.py -> build/lib/openpyn
copying openpyn/credentials.py -> build/lib/openpyn
copying openpyn/firewall.py -> build/lib/openpyn
copying openpyn/converter.py -> build/lib/openpyn
copying openpyn/root.py -> build/lib/openpyn
copying openpyn/openpyn.py -> build/lib/openpyn
copying openpyn/api.py -> build/lib/openpyn
copying openpyn/locations.py -> build/lib/openpyn
copying openpyn/__main__.py -> build/lib/openpyn
copying openpyn/asus.py -> build/lib/openpyn
copying openpyn/systemd.py -> build/lib/openpyn
copying openpyn/filters.py -> build/lib/openpyn
copying openpyn/initd.py -> build/lib/openpyn
creating build/lib/tests
copying tests/__init__.py -> build/lib/tests
copying tests/test_openpyn.py -> build/lib/tests
running egg_info
creating openpyn.egg-info
writing openpyn.egg-info/PKG-INFO
writing dependency_links to openpyn.egg-info/dependency_links.txt
writing entry points to openpyn.egg-info/entry_points.txt
writing requirements to openpyn.egg-info/requires.txt
writing top-level names to openpyn.egg-info/top_level.txt
writing manifest file 'openpyn.egg-info/SOURCES.txt'
reading manifest file 'openpyn.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files found matching 'openpyn/test.py'
no previously-included directories found matching 'openpyn/management/__pycache__'
no previously-included directories found matching '.git'
no previously-included directories found matching 'openpyn/files'
writing manifest file 'openpyn.egg-info/SOURCES.txt'
copying openpyn/config.json -> build/lib/openpyn
creating build/lib/openpyn/management
copying openpyn/management/management.py -> build/lib/openpyn/management
creating build/lib/openpyn/scripts
copying openpyn/scripts/manual-dns-patch.sh -> build/lib/openpyn/scripts
copying openpyn/scripts/update-resolv-conf.sh -> build/lib/openpyn/scripts
copying openpyn/scripts/update-systemd-resolved.sh -> build/lib/openpyn/scripts
==> Entering fakeroot environment...
==> Starting package()...
running install
running install_lib
creating /home/atom/.cache/yay/openpyn-nordvpn/pkg/openpyn-nordvpn/usr
creating /home/atom/.cache/yay/openpyn-nordvpn/pkg/openpyn-nordvpn/usr/lib
creating /home/atom/.cache/yay/openpyn-nordvpn/pkg/openpyn-nordvpn/usr/lib/python3.8
creating /home/atom/.cache/yay/openpyn-nordvpn/pkg/openpyn-nordvpn/usr/lib/python3.8/site-packages
creating /home/atom/.cache/yay/openpyn-nordvpn/pkg/openpyn-nordvpn/usr/lib/python3.8/site-packages/openpyn
copying build/lib/openpyn/config.json -> /home/atom/.cache/yay/openpyn-nordvpn/pkg/openpyn-nordvpn/usr/lib/python3.8/site-packages/openpyn
copying build/lib/openpyn/__init__.py -> /home/atom/.cache/yay/openpyn-nordvpn/pkg/openpyn-nordvpn/usr/lib/python3.8/site-packages/openpyn
copying build/lib/openpyn/credentials.py -> /home/atom/.cache/yay/openpyn-nordvpn/pkg/openpyn-nordvpn/usr/lib/python3.8/site-packages/openpyn
creating /home/atom/.cache/yay/openpyn-nordvpn/pkg/openpyn-nordvpn/usr/lib/python3.8/site-packages/openpyn/scripts
copying build/lib/openpyn/scripts/update-resolv-conf.sh -> /home/atom/.cache/yay/openpyn-nordvpn/pkg/openpyn-nordvpn/usr/lib/python3.8/site-packages/openpyn/scripts
copying build/lib/openpyn/scripts/update-systemd-resolved.sh -> /home/atom/.cache/yay/openpyn-nordvpn/pkg/openpyn-nordvpn/usr/lib/python3.8/site-packages/openpyn/scripts
copying build/lib/openpyn/scripts/manual-dns-patch.sh -> /home/atom/.cache/yay/openpyn-nordvpn/pkg/openpyn-nordvpn/usr/lib/python3.8/site-packages/openpyn/scripts
copying build/lib/openpyn/firewall.py -> /home/atom/.cache/yay/openpyn-nordvpn/pkg/openpyn-nordvpn/usr/lib/python3.8/site-packages/openpyn
copying build/lib/openpyn/converter.py -> /home/atom/.cache/yay/openpyn-nordvpn/pkg/openpyn-nordvpn/usr/lib/python3.8/site-packages/openpyn
copying build/lib/openpyn/root.py -> /home/atom/.cache/yay/openpyn-nordvpn/pkg/openpyn-nordvpn/usr/lib/python3.8/site-packages/openpyn
copying build/lib/openpyn/openpyn.py -> /home/atom/.cache/yay/openpyn-nordvpn/pkg/openpyn-nordvpn/usr/lib/python3.8/site-packages/openpyn
copying build/lib/openpyn/api.py -> /home/atom/.cache/yay/openpyn-nordvpn/pkg/openpyn-nordvpn/usr/lib/python3.8/site-packages/openpyn
copying build/lib/openpyn/locations.py -> /home/atom/.cache/yay/openpyn-nordvpn/pkg/openpyn-nordvpn/usr/lib/python3.8/site-packages/openpyn
copying build/lib/openpyn/__main__.py -> /home/atom/.cache/yay/openpyn-nordvpn/pkg/openpyn-nordvpn/usr/lib/python3.8/site-packages/openpyn
copying build/lib/openpyn/asus.py -> /home/atom/.cache/yay/openpyn-nordvpn/pkg/openpyn-nordvpn/usr/lib/python3.8/site-packages/openpyn
creating /home/atom/.cache/yay/openpyn-nordvpn/pkg/openpyn-nordvpn/usr/lib/python3.8/site-packages/openpyn/management
copying build/lib/openpyn/management/management.py -> /home/atom/.cache/yay/openpyn-nordvpn/pkg/openpyn-nordvpn/usr/lib/python3.8/site-packages/openpyn/management
copying build/lib/openpyn/systemd.py -> /home/atom/.cache/yay/openpyn-nordvpn/pkg/openpyn-nordvpn/usr/lib/python3.8/site-packages/openpyn
copying build/lib/openpyn/filters.py -> /home/atom/.cache/yay/openpyn-nordvpn/pkg/openpyn-nordvpn/usr/lib/python3.8/site-packages/openpyn
copying build/lib/openpyn/initd.py -> /home/atom/.cache/yay/openpyn-nordvpn/pkg/openpyn-nordvpn/usr/lib/python3.8/site-packages/openpyn
creating /home/atom/.cache/yay/openpyn-nordvpn/pkg/openpyn-nordvpn/usr/lib/python3.8/site-packages/tests
copying build/lib/tests/__init__.py -> /home/atom/.cache/yay/openpyn-nordvpn/pkg/openpyn-nordvpn/usr/lib/python3.8/site-packages/tests
copying build/lib/tests/test_openpyn.py -> /home/atom/.cache/yay/openpyn-nordvpn/pkg/openpyn-nordvpn/usr/lib/python3.8/site-packages/tests
byte-compiling /home/atom/.cache/yay/openpyn-nordvpn/pkg/openpyn-nordvpn/usr/lib/python3.8/site-packages/openpyn/__init__.py to __init__.cpython-38.pyc
byte-compiling /home/atom/.cache/yay/openpyn-nordvpn/pkg/openpyn-nordvpn/usr/lib/python3.8/site-packages/openpyn/credentials.py to credentials.cpython-38.pyc
byte-compiling /home/atom/.cache/yay/openpyn-nordvpn/pkg/openpyn-nordvpn/usr/lib/python3.8/site-packages/openpyn/firewall.py to firewall.cpython-38.pyc
byte-compiling /home/atom/.cache/yay/openpyn-nordvpn/pkg/openpyn-nordvpn/usr/lib/python3.8/site-packages/openpyn/converter.py to converter.cpython-38.pyc
byte-compiling /home/atom/.cache/yay/openpyn-nordvpn/pkg/openpyn-nordvpn/usr/lib/python3.8/site-packages/openpyn/root.py to root.cpython-38.pyc
byte-compiling /home/atom/.cache/yay/openpyn-nordvpn/pkg/openpyn-nordvpn/usr/lib/python3.8/site-packages/openpyn/openpyn.py to openpyn.cpython-38.pyc
byte-compiling /home/atom/.cache/yay/openpyn-nordvpn/pkg/openpyn-nordvpn/usr/lib/python3.8/site-packages/openpyn/api.py to api.cpython-38.pyc
byte-compiling /home/atom/.cache/yay/openpyn-nordvpn/pkg/openpyn-nordvpn/usr/lib/python3.8/site-packages/openpyn/locations.py to locations.cpython-38.pyc
byte-compiling /home/atom/.cache/yay/openpyn-nordvpn/pkg/openpyn-nordvpn/usr/lib/python3.8/site-packages/openpyn/__main__.py to __main__.cpython-38.pyc
byte-compiling /home/atom/.cache/yay/openpyn-nordvpn/pkg/openpyn-nordvpn/usr/lib/python3.8/site-packages/openpyn/asus.py to asus.cpython-38.pyc
byte-compiling /home/atom/.cache/yay/openpyn-nordvpn/pkg/openpyn-nordvpn/usr/lib/python3.8/site-packages/openpyn/management/management.py to management.cpython-38.pyc
byte-compiling /home/atom/.cache/yay/openpyn-nordvpn/pkg/openpyn-nordvpn/usr/lib/python3.8/site-packages/openpyn/systemd.py to systemd.cpython-38.pyc
byte-compiling /home/atom/.cache/yay/openpyn-nordvpn/pkg/openpyn-nordvpn/usr/lib/python3.8/site-packages/openpyn/filters.py to filters.cpython-38.pyc
byte-compiling /home/atom/.cache/yay/openpyn-nordvpn/pkg/openpyn-nordvpn/usr/lib/python3.8/site-packages/openpyn/initd.py to initd.cpython-38.pyc
byte-compiling /home/atom/.cache/yay/openpyn-nordvpn/pkg/openpyn-nordvpn/usr/lib/python3.8/site-packages/tests/__init__.py to __init__.cpython-38.pyc
byte-compiling /home/atom/.cache/yay/openpyn-nordvpn/pkg/openpyn-nordvpn/usr/lib/python3.8/site-packages/tests/test_openpyn.py to test_openpyn.cpython-38.pyc
writing byte-compilation script '/tmp/tmpsbkzizez.py'
/usr/bin/python /tmp/tmpsbkzizez.py
removing /tmp/tmpsbkzizez.py
running install_egg_info
running egg_info
writing openpyn.egg-info/PKG-INFO
writing dependency_links to openpyn.egg-info/dependency_links.txt
writing entry points to openpyn.egg-info/entry_points.txt
writing requirements to openpyn.egg-info/requires.txt
writing top-level names to openpyn.egg-info/top_level.txt
reading manifest file 'openpyn.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files found matching 'openpyn/test.py'
no previously-included directories found matching 'openpyn/management/__pycache__'
no previously-included directories found matching '.git'
no previously-included directories found matching 'openpyn/files'
writing manifest file 'openpyn.egg-info/SOURCES.txt'
Copying openpyn.egg-info to /home/atom/.cache/yay/openpyn-nordvpn/pkg/openpyn-nordvpn/usr/lib/python3.8/site-packages/openpyn-2.7.5-py3.8.egg-info
running install_scripts
Installing openpyn script to /home/atom/.cache/yay/openpyn-nordvpn/pkg/openpyn-nordvpn/usr/bin
Installing openpyn-management script to /home/atom/.cache/yay/openpyn-nordvpn/pkg/openpyn-nordvpn/usr/bin
==> Tidying install...
  -> Removing libtool files...
  -> Purging unwanted files...
  -> Removing static library files...
  -> Stripping unneeded symbols from binaries and libraries...
  -> Compressing man and info pages...
==> Checking for packaging issues...
==> Creating package "openpyn-nordvpn"...
  -> Generating .PKGINFO file...
  -> Generating .BUILDINFO file...
  -> Adding install file...
  -> Generating .MTREE file...
  -> Compressing package...
==> Leaving fakeroot environment.
==> Finished making: openpyn-nordvpn 2.2.0.r314.g0b40481-1 (Thu 19 Dec 2019 06:37:26 AM EST)
==> Cleaning up...
==> Found git repo: github.com/jotyGill/openpyn-nordvpn.git
loading packages...
resolving dependencies...
looking for conflicting packages...

Packages (1) openpyn-nordvpn-2.2.0.r314.g0b40481-1

Total Installed Size:  0.36 MiB

:: Proceed with installation? [Y/n] 
(1/1) checking keys in keyring                        [############################] 100%
(1/1) checking package integrity                      [############################] 100%
(1/1) loading package files                           [############################] 100%
(1/1) checking for file conflicts                     [############################] 100%
(1/1) checking available disk space                   [############################] 100%
:: Processing package changes...
(1/1) installing openpyn-nordvpn                      [############################] 100%
---------------------------------------------------
==> Run 'sudo openpyn --init' to initialize openpyn
---------------------------------------------------
:: Running post-transaction hooks...
(1/1) Arming ConditionNeedsUpdate...
[atom@atom-pc ~]$ openpyn --help
Traceback (most recent call last):
  File "/usr/bin/openpyn", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3252, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3235, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3264, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'verboselogs' distribution was not found and is required by openpyn
[atom@atom-pc ~]$ sudo python -m pip install python-verboselogs
[sudo] password for atom: 
Collecting python-verboselogs
  ERROR: Could not find a version that satisfies the requirement python-verboselogs (from versions: none)
ERROR: No matching distribution found for python-verboselogs
```

</details>

**Comment by jotyGill** [comment]
Missed your comment.

my bad the package is published as `verboselogs` not `python-verboselogs`
You might want to uninstall all requirements then reinstalled openpyn (it will get requirements as well).
`install_requires=['colorama', 'coloredlogs', 'jsonschema', 'requests', 'tqdm', 'verboselogs'],`

Hopefully your distro have fixed the mess up by now?

**Comment by atomGit** [comment]
> Hopefully your distro have fixed the mess up by now?

apparently so - i dumped the openpyn package and installed with...

`$ sudo python3 -m pip install --upgrade openpyn`

and all went smooth

**Comment by albaphysic** [comment]
This issue still pops up every python upgrade. The issue isn't with the package per-se:

https://www.reddit.com/r/archlinux/comments/5mer2f/psa_rebuild_all_aur_packages_providing_python/

> The issue is that the current set of Python library AUR packages on your system have most likely been built with Python 3.5 and setuptools, causing them to (still) be installed into /usr/lib/python3.5; after the upgrade to Python 3.6, the Python interpreter won't be searching this path anymore for imports, potentially causing programs that rely on these packages to fail.

>The official packages don't have this problem, because the maintainers took care to version bump all Python packages for you when the upgrade to Python 3.6 took place.

Solution:
`yay -S --rebuildall aur/python-verboselogs`
`yay -S --rebuildall aur/openpyn-nordvpn`
