### ISSUE TITLE
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by mdelain** [jotyGill/openpyn-nordvpn#281]
Hello,

I'm having a similar issue to the recent #279 on Raspberry Pi 3b (latest release):
```
Traceback (most recent call last):
  File "/usr/local/bin/openpyn", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/openpyn/openpyn.py", line 144, in main
    args.skip_dns_patch, args.silent, args.nvram, args.openvpn_options, args.location)
  File "/usr/local/lib/python3.7/dist-packages/openpyn/openpyn.py", line 395, in run
    dedicated, double_vpn, tor_over_vpn, anti_ddos, netflix, location, stats)
  File "/usr/local/lib/python3.7/dist-packages/openpyn/openpyn.py", line 473, in find_better_servers
    netflix=netflix, location=location)
  File "/usr/local/lib/python3.7/dist-packages/openpyn/api.py", line 38, in get_data_from_api
    json_response = get_json(url)
  File "/usr/local/lib/python3.7/dist-packages/openpyn/api.py", line 20, in get_json
    json_response = requests.get(url, headers=headers).json()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
Any hint?

**Comment by 1951FDG** [comment]
Hello,

This is new, the API (https://api.nordvpn.com/server) is being rate-limited.

Basically, we are being banned temporarily from accessing this website.

**Comment by mdelain** [comment]
Thanks for the explanation. I hope this is only temporary...
Today it seems to work for me using the manual command line, I'll try tomorrow reinstalling the service.

**Comment by 1951FDG** [comment]
Upon further investigation, Openpyn, is calling the API twice within a very short period of time.

> find_better_servers > api.get_data_from_api
> api.get_country_code

We need to call the api only once during execution and store the result thereof in memory.

I'm thinking best would be to turn _api.py_ to a python class.

We need to rewrite the code somewhat, since we now need to respect the rate-limits.

@jotyGill Hi, would you like me to code the changes required, I can then push to test branch, this time however, we may need to finally merge master and test branch, since with rate-limiting being active, the current release is broken.

**Comment by 1951FDG** [comment]
This is definitely or most likely not temporary.

API rate limiting is new, and will most likely stay as is.

My test branch, contains a fix for this, and now allows openpyn to cache the API result for 5 minutes
```bash
git clone --branch test https://github.com/1951FDG/openpyn-nordvpn.git
cd openpyn-nordvpn/
python3 -m pip install --upgrade .
```

**Comment by 1951FDG** [comment]
This has been pushed to the master branch, please update to at least openpyn 3.0.0!
