### ISSUE TITLE
OpenWrt 19.07.4, r11208-ce6496d796

### ISSUE THREAD

**Issue by Kitty-Shackleford** [jotyGill/openpyn-nordvpn#288]
```
Traceback (most recent call last):
 
File "/usr/bin/openpyn", line 8, in <module> sys.exit(main())

File "/usr/lib/python3.7/site-packages/openpyn/openpyn.py", line 187, in main args.show_status, args.show_stats)

File "/usr/lib/python3.7/site-packages/openpyn/openpyn.py", line 299, in run  initialise(detected_os, asuswrt_os, openwrt_os)

File "/usr/lib/python3.7/site-packages/openpyn/openpyn.py", line 675, in initialise initd.install_service()
  
File "/usr/lib/python3.7/site-packages/openpyn/initd.py", line 179, in install_service update_service(openpyn_options)
  
File "/usr/lib/python3.7/site-packages/openpyn/initd.py", line 185, in update_service os.chmod("/opt/etc/init.d/S23openpyn", 0o755)

FileNotFoundError: [Errno 2] No such file or directory: '/opt/etc/init.d/S23openpyn'
```

So, I had this working but now IDK what happened but I am getting these error messages...

Clean install of OpenWRT with exrooted drive. Again I had installed this last year and it was pretty straight forward but now I am stuck and I really like this for my VPN!

**Comment by Kitty-Shackleford** [comment]
adding the file "S23openpyn"  to DIR "'/opt/etc/init.d/" seemed to fix this...
