### ISSUE TITLE
August 5 commit causes error and fails

### ISSUE THREAD

**Issue by foopex** [jotyGill/openpyn-nordvpn#42]
I pulled the august 5 commit, and I get an error using the following command line(works with prior commits):
sudo openpyn us -u -f --skip-dns-patch --allow 22 80 443 3128 8112 58846 -t 10 -T 2 -d --p2p

Error:

```
Flushing iptables INPUT and OUTPUT chains AND Applying default Rules
...SNIP...
Top 2 Servers with best Ping are: ['us650', 'us505']
Traceback (most recent call last):
  File "/usr/local/bin/openpyn", line 11, in <module>
    load_entry_point('openpyn==1.6.0', 'console_scripts', 'openpyn')()
  File "/usr/local/lib/python3.5/dist-packages/openpyn-1.6.0-py3.5.egg/openpyn/openpyn.py", line 118, in main
    args.skip_dns_patch)
  File "/usr/local/lib/python3.5/dist-packages/openpyn-1.6.0-py3.5.egg/openpyn/openpyn.py", line 203, in run
    vpn_server_ip = get_vpn_server_ip(chosen_servers, port)
  File "/usr/local/lib/python3.5/dist-packages/openpyn-1.6.0-py3.5.egg/openpyn/openpyn.py", line 527, in get_vpn_server_ip
    file_path = "/usr/share/openpyn/files/" + server + ".nordvpn.com." + port + ".ovpn"
TypeError: Can't convert 'list' object to str implicitly
```

**Comment by jotyGill** [comment]
yeah, my bad. I was playing with the feature of iterating through a list of servers if connection to one fails and openvpn exits. Should be all good now.

**Comment by foopex** [comment]
Back to normal, thanks!
