### ISSUE TITLE
Area Connect not possible

### ISSUE THREAD

**Issue by ampfinger** [jotyGill/openpyn-nordvpn#64]
Hey,

If I use for example "openpyn us -a ny" I got this output:
`Traceback (most recent call last):
  File "/usr/local/bin/openpyn", line 9, in <module>
    load_entry_point('openpyn==1.7.3', 'console_scripts', 'openpyn')()
  File "/usr/local/lib/python3.4/dist-packages/openpyn-1.7.3-py3.4.egg/openpyn/openpyn.py", line 116, in main
    args.skip_dns_patch)
  File "/usr/local/lib/python3.4/dist-packages/openpyn-1.7.3-py3.4.egg/openpyn/openpyn.py", line 191, in run
    dedicated, double_vpn, tor_over_vpn, anti_ddos)
  File "/usr/local/lib/python3.4/dist-packages/openpyn-1.7.3-py3.4.egg/openpyn/openpyn.py", line 293, in find_better_servers
    double_vpn=double_vpn, tor_over_vpn=tor_over_vpn, anti_ddos=anti_ddos)
  File "/usr/local/lib/python3.4/dist-packages/openpyn-1.7.3-py3.4.egg/openpyn/openpyn.py", line 276, in get_data_from_api
    type_country_area_filtered = filters.filter_by_area(area, type_country_filtered)
  File "/usr/local/lib/python3.4/dist-packages/openpyn-1.7.3-py3.4.egg/openpyn/filters.py", line 8, in filter_by_area
    resolved_locations = locations.get_unique_locations(list_of_servers=type_country_filtered)
  File "/usr/local/lib/python3.4/dist-packages/openpyn-1.7.3-py3.4.egg/openpyn/locations.py", line 14, in get_unique_locations
    geo_address_list = get_location_name(eachLocation)
  File "/usr/local/lib/python3.4/dist-packages/openpyn-1.7.3-py3.4.egg/openpyn/locations.py", line 34, in get_location_name
    results = r.json()['results'][0]['address_components']
IndexError: list index out of range`

Connection with country only is no problem.

**Comment by jotyGill** [comment]
seems like Google is limiting the requests to their API more strictly. I just rebooted my router and grabbed new IP and now it's working (and it quickly gets blocked). I might have to switch to some other service like openstreetmaps?

**Comment by ampfinger** [comment]
Would be nice if it could be realized.
Thanks for your hard work :)
