### ISSUE TITLE
IndexError: list index out of range after openpyn -l --p2p

### ISSUE THREAD

**Issue by Kipjr** [jotyGill/openpyn-nordvpn#68]
`user@hostname:~$ openpyn -l --p2p`

(list of servers)

`Traceback (most recent call last):
  File "/usr/local/bin/openpyn", line 9, in <module>
    load_entry_point('openpyn==1.7.3', 'console_scripts', 'openpyn')()
  File "/usr/local/lib/python3.5/dist-packages/openpyn-1.7.3-py3.5.egg/openpyn/openpyn.py", line 116, in main
    args.skip_dns_patch)
  File "/usr/local/lib/python3.5/dist-packages/openpyn-1.7.3-py3.5.egg/openpyn/openpyn.py", line 156, in run
    double_vpn=double_vpn, tor_over_vpn=tor_over_vpn, anti_ddos=anti_ddos)
  File "/usr/local/lib/python3.5/dist-packages/openpyn-1.7.3-py3.5.egg/openpyn/openpyn.py", line 436, in display_servers
    locations_in_country = locations.get_unique_locations(list_of_servers=json_res_list)
  File "/usr/local/lib/python3.5/dist-packages/openpyn-1.7.3-py3.5.egg/openpyn/locations.py", line 14, in get_unique_locations
    geo_address_list = get_location_name(eachLocation)
  File "/usr/local/lib/python3.5/dist-packages/openpyn-1.7.3-py3.5.egg/openpyn/locations.py", line 34, in get_location_name
    results = r.json()['results'][0]['address_components']
IndexError: list index out of range`

I understood that this was due to the fact that the API of Google has a limit, _which is 50 requests per second, calculated as the sum of client-side and server-side queries._ [Link](https://developers.google.com/maps/documentation/geocoding/usage-limit)

Is it possible to limit these requests in the software so no error messages will be generated?

**Comment by Kipjr** [comment]
`time.sleep(1/50)` after each request?

**Comment by jotyGill** [comment]
I see so limit is 50 requests per second, in that case i'll try sleeping for a bit.
